version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=012345678
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./mysql.conf.d:/etc/mysql/mysql.conf.d
      - ./data:/var/lib/mysql
      - ./compartido:/compartido
      - ./database/db-dump:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro