apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-docker
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup-docker
            image: 192.168.1.150:5000/cleanup:01
            volumeMounts:
            - name: socket-docker
              mountPath: /var/run/docker.sock
              readOnly: false
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred
          volumes:
            - name: socket-docker
              hostPath:
                path: "/var/run/docker.sock"
