FROM ubuntu:18.04
MAINTAINER eltano <ghcetraro@gmail.com>

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
RUN curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey 
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable" 
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce

COPY cleanup.sh /
RUN chmod 755 /cleanup.sh

CMD /cleanup.sh
