FROM 123.176.93.6:5000/ubuntu:18.04
MAINTAINER eltano <ghcetraro@gmail.com>

COPY proxy.conf /etc/apt/apt.conf.d/

# Install apache
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install apache2 net-tools nano

# Enable apache mods.
RUN a2enmod rewrite

COPY index.html /var/www/html/

# Manually set up the apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

# Expose apache.
EXPOSE 80 443

RUN a2ensite 000-default.conf

# By default start up apache in the foreground, override with /bin/bash for interative.
CMD /usr/sbin/apache2ctl -D FOREGROUND

